version: '3.6'
services:
  node:
    image: node:21.7
    container_name: node
    user: "node"
    working_dir: /usr/node/app
    environment:
      - NODE_ENV=development
      - NPM_TOKEN=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
    restart: always
    volumes:
      - ./:/usr/node/app
    ports:
      - 8080:8080
    command: bash -c "npm install && npm run build && npm start"
